### PR TITLE
Cleaning up css

### PR DESCRIPTION
**Pull request by nmkettler**
I removed react-bootstrap cols and added regular bootstrap classes to account for offsets.

### CODE REVIEW

**Comment by TheOdd** [comment]
Everything looks good so far, just one thing that I noticed when running it on my local machine: the information button next to each entry in the list isn't being resized by the font size attribute in the CSS. I don't think the 0.553em is affecting them in the CSS file, so you might want to look at that again.

**Comment by TheOdd** [comment]
There's also a warning in the console about valid DOM nesting when opening any of the modals.

    Warning: validateDOMNesting(...): <h1> cannot appear as a child of <h4>. See CodesList > ModalTitle > h4 > h1.

**Comment by nmkettler** [comment]
@TheOdd That error should no longer be appearing. Modal.title had was being set as an h1 so I removed the h1 within the tags. I also added react-redux and redux to the package.json to make it a little easier to install. I had to install them separately when I started the project.

**Comment by TheOdd** [comment]
@nmkettler Alright. I'm not able to locally run the PR right now, so can you compare the two end results of the web app before and after your changes to see if it looks the same on the frontend side? Like if the modal text sizes and weight stayed the same and button sizes, etc. If it all looks ok, I'd be ready to merge.

**Comment by nmkettler** [comment]
@TheOdd everything looks to have stayed the same when I look at it.

**Comment by TheOdd** [comment]
Look good to me. Merging.

**Pull request merged**
